// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlataformaEducativa.Models;

#nullable disable

namespace PlataformaEducativa.Migrations
{
    [DbContext(typeof(PlataformaEducativaDbContext))]
    [Migration("20231220192648_v5")]
    partial class v5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlataformaEducativa.Models.CursoNota", b =>
                {
                    b.Property<int>("CursoNotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoNotaId"), 1L, 1);

                    b.Property<int>("EstudiantesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IniciarCursoId")
                        .HasColumnType("int");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("CursoNotaId");

                    b.HasIndex("EstudiantesId");

                    b.HasIndex("IniciarCursoId");

                    b.ToTable("CursoNota");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.CursoParticipante", b =>
                {
                    b.Property<int>("CursoParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoParticipanteId"), 1L, 1);

                    b.Property<int>("EstudiantesId")
                        .HasColumnType("int");

                    b.Property<int>("IniciarCursoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("CursoParticipanteId");

                    b.HasIndex("EstudiantesId");

                    b.HasIndex("IniciarCursoId");

                    b.ToTable("CursoParticipante");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.CursoProfesor", b =>
                {
                    b.Property<int>("CursoProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoProfesorId"), 1L, 1);

                    b.Property<int>("IniciarCursoId")
                        .HasColumnType("int");

                    b.Property<bool>("Termino")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CursoProfesorId");

                    b.HasIndex("IniciarCursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cursoProfesors");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Cursos", b =>
                {
                    b.Property<int>("CursosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursosId"), 1L, 1);

                    b.Property<string>("CursosName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CursosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.DiaSemana", b =>
                {
                    b.Property<int>("DiaSemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaSemanaId"), 1L, 1);

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiaSemanaId");

                    b.ToTable("dia_Semana");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.DiaSemanaCurso", b =>
                {
                    b.Property<int>("DiaSemanaCursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaSemanaCursoId"), 1L, 1);

                    b.Property<int>("DiaSemanaId")
                        .HasColumnType("int");

                    b.Property<int>("IniciarCursoId")
                        .HasColumnType("int");

                    b.HasKey("DiaSemanaCursoId");

                    b.HasIndex("DiaSemanaId");

                    b.HasIndex("IniciarCursoId");

                    b.ToTable("diaSemanaCursos");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudiantesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudiantesId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("InstitucionesId")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Verificar")
                        .HasColumnType("bit");

                    b.HasKey("EstudiantesId");

                    b.HasIndex("InstitucionesId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Hora", b =>
                {
                    b.Property<int>("HoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoraId"), 1L, 1);

                    b.Property<string>("AMPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CatidadHora")
                        .HasColumnType("int");

                    b.Property<string>("Horas_Final")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Horas_Iniciar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoraId");

                    b.ToTable("Horas");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.IniciarCurso", b =>
                {
                    b.Property<int>("IniciarCursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IniciarCursoId"), 1L, 1);

                    b.Property<byte>("Activo")
                        .HasColumnType("tinyint");

                    b.Property<int>("CursosId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaIniciar")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Finaliza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Finalizo")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoraId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HoraIniciar")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HoraTerminar")
                        .HasColumnType("time");

                    b.Property<int>("InstitucionesId")
                        .HasColumnType("int");

                    b.Property<byte?>("Termino")
                        .HasColumnType("tinyint");

                    b.HasKey("IniciarCursoId");

                    b.HasIndex("CursosId");

                    b.HasIndex("HoraId");

                    b.HasIndex("InstitucionesId");

                    b.ToTable("iniciarCurso");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Instituciones", b =>
                {
                    b.Property<int>("InstitucionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitucionesId"), 1L, 1);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gestor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstitucionesId");

                    b.ToTable("instituciones");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.List_Est_Curso", b =>
                {
                    b.Property<int>("List_Est_CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("List_Est_CursoId"), 1L, 1);

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudiantesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstitucioneId")
                        .HasColumnType("int");

                    b.HasKey("List_Est_CursoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudiantesId");

                    b.HasIndex("InstitucioneId");

                    b.ToTable("List_Est_Curso");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipioId"), 1L, 1);

                    b.Property<string>("MunicipioName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MunicipioId");

                    b.ToTable("municipio");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("RolesId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Confirmar")
                        .HasColumnType("tinyint");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("InstitucionesId")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("InstitucionesId");

                    b.HasIndex("RolesId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Usuario_Materia", b =>
                {
                    b.Property<int>("Usuario_MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usuario_MateriaId"), 1L, 1);

                    b.Property<int>("CursosId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Usuario_MateriaId");

                    b.HasIndex("CursosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuario_Materias");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.CursoNota", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Estudiantes", "Estudiantes")
                        .WithMany()
                        .HasForeignKey("EstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.IniciarCurso", "IniciarCurso")
                        .WithMany()
                        .HasForeignKey("IniciarCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiantes");

                    b.Navigation("IniciarCurso");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.CursoParticipante", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Estudiantes", "Estudiantes")
                        .WithMany()
                        .HasForeignKey("EstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.IniciarCurso", "IniciarCurso")
                        .WithMany()
                        .HasForeignKey("IniciarCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiantes");

                    b.Navigation("IniciarCurso");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.CursoProfesor", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.IniciarCurso", "IniciarCurso")
                        .WithMany()
                        .HasForeignKey("IniciarCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IniciarCurso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Cursos", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.DiaSemanaCurso", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.DiaSemana", "DiaSemana")
                        .WithMany()
                        .HasForeignKey("DiaSemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.IniciarCurso", "IniciarCurso")
                        .WithMany()
                        .HasForeignKey("IniciarCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaSemana");

                    b.Navigation("IniciarCurso");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Estudiantes", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Instituciones", "Instituciones")
                        .WithMany()
                        .HasForeignKey("InstitucionesId");

                    b.HasOne("PlataformaEducativa.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituciones");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.IniciarCurso", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Cursos", "Cursos")
                        .WithMany()
                        .HasForeignKey("CursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Hora", "Hora")
                        .WithMany()
                        .HasForeignKey("HoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Instituciones", "Instituciones")
                        .WithMany()
                        .HasForeignKey("InstitucionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursos");

                    b.Navigation("Hora");

                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.List_Est_Curso", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Cursos", "Cursos")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Estudiantes", "Estudiantes")
                        .WithMany()
                        .HasForeignKey("EstudiantesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Instituciones", "Instituciones")
                        .WithMany()
                        .HasForeignKey("InstitucioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursos");

                    b.Navigation("Estudiantes");

                    b.Navigation("Instituciones");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Usuario", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Instituciones", "Instituciones")
                        .WithMany()
                        .HasForeignKey("InstitucionesId");

                    b.HasOne("PlataformaEducativa.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituciones");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PlataformaEducativa.Models.Usuario_Materia", b =>
                {
                    b.HasOne("PlataformaEducativa.Models.Cursos", "Cursos")
                        .WithMany()
                        .HasForeignKey("CursosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlataformaEducativa.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursos");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
